# -*- coding: utf-8 -*-
"""teste2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JHQbrEkf68FpbfUw7pZiO1nTn0UMzqn_
"""

def imc2():
  nome = input('Digite seu nome: ')
  peso = float(input('Informe seu peso em KG: '))
  altura = float(input('Informe sua altura em metros: '))
  imc2 = peso/altura**2
  #return print(nome, 'tem o IMC de:', {imc2}, '!!!')
  return print(f'O resultado é {imc2:.2f}')