# -*- coding: utf-8 -*-
"""teste.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Os_cmAS2fvkvziHyY6XjY0OkykyPgKn7
"""

def imc():
  peso = float(input('Informe seu peso em KG: '))
  altura = float(input('Informe sua altura em metros: '))
  imc = peso/altura**2
  return imc